# Generated by Django 2.1.5 on 2019-04-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20190405_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ManyToManyField(to='tweets.Post'),
        ),
    ]
