# Generated by Django 2.1.5 on 2019-04-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20190405_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.Post'),
        ),
    ]
