# Generated by Django 2.1.5 on 2019-04-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20190406_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Post'),
        ),
    ]
